apiVersion: v1 
kind: Secret 
metadata: 
  name: capmaas-manager-bootstrap-credentials 
  namespace: capmaas-system 
  labels:
    cluster.x-k8s.io/provider: infrastructure-maas
type: Opaque 
stringData: 
  MAAS_ENDPOINT: endpoint_goes_here
  MAAS_API_KEY: api_key_goes_here
