
apiVersion: v1 
kind: Namespace
metadata:
  name: system

---

apiVersion: v1 
kind: Secret 
metadata: 
  name: manager-bootstrap-credentials 
  namespace: system 
type: Opaque 
stringData: 
  MAAS_ENDPOINT: endpoint_goes_here
  MAAS_API_KEY: api_key_goes_here