# Creates a cluster with one control-plane node and one worker node
 
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
 
kind: MaasCluster
metadata: 
  name: my-cluster 
spec: 
  dnsDomain: maas
 
---
 
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster 
metadata: 
  name: my-cluster 
spec: 
  clusterNetwork: 
    services: 
      cidrBlocks: ["10.96.0.0/12"] 
    pods: 
      cidrBlocks: ["192.168.0.0/16"] 
    serviceDomain: "cluster.local" 
  controlPlaneRef: 
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: KubeadmControlPlane 
    name: my-cluster-cp 
    namespace: default 
  infrastructureRef: 
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: MaasCluster 
    name: my-cluster 
    namespace: default
 
---
 
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: MaasMachineTemplate 
metadata: 
  name: my-cluster-cp 
  namespace: default 
spec: 
  template: 
    spec: 
      minCPU: 2 
      minMemory: 3072
      image: ubuntu/focal 
---
 
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: KubeadmControlPlane 
metadata: 
  name: my-cluster-cp 
  namespace: default 
spec: 
  replicas: 1 
  version: v1.19.12 
  machineTemplate: 
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
      kind: MaasMachineTemplate 
      name: my-cluster-cp 
      namespace: default 
  kubeadmConfigSpec: 
    clusterConfiguration: {} 
    initConfiguration: {} 
    joinConfiguration: {}
 
